Repository willyyhuang/soen-343, pull requests merged in 2020-11, with the labels that each got.

#73 Setup auto mode for lights
  HomeLayoutExample.json
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/SimulationContextController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/SmartHomeCoreFunctionalityController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/UserController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/HomeLayout.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/Room.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/roomObjects/Door.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/roomObjects/Light.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/roomObjects/RoomObject.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/roomObjects/Window.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SimulationContext.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeCoreFunctionality.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/SimulationContextService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/SmartHomeCoreFunctionalityService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/UserService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/test/java/com/project/SmartHomeSimulator/service/SimulationContextServiceTest.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/test/java/com/project/SmartHomeSimulator/service/SmartHomeCoreFunctionalityServiceTest.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/test/java/com/project/SmartHomeSimulator/service/UserServiceTest.java
Labels: Delivery 2, SHC, Testing, bug, enhancement

#76 door has been set up
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/SmartHomeCoreFunctionalityController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeCoreFunctionality.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/SmartHomeCoreFunctionalityService.java
Labels: Delivery 2, SHC

#78 new home layout
  HomeLayoutExample.json
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/HomeLayout.java
Labels: bug

#79 Setup SHP
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/SimulationHomeSecurityController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/SmartHomeCoreFunctionalityController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/UserController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/HomeLayout.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/ResponseAPI.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/Module.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/PermissionVerifier.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SimulationContext.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeCoreFunctionality.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeCoreFunctionalityProxy.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeSecurity.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeSecurityProxy.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/SmartHomeCoreFunctionalityService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/SmartHomeSecurityService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/UserService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/test/java/com/project/SmartHomeSimulator/service/SimulationContextServiceTest.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/test/java/com/project/SmartHomeSimulator/service/UserServiceTest.java
Labels: Delivery 2, SHP

#82 Saving profiles to json file
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/UserController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/User.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SimulationContext.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/UserService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/resources/user_profiles.json.txt
Labels: Delivery 2, SHS

#83 Updated SHP controllers
  SmartHomeSimulatorBack/SmartHomeSimulator/SmartHomeSecurity.txt
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/SimulationHomeSecurityController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/HomeLayout.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/Module.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeSecurity.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeSecurityProxy.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/SmartHomeSecurityService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/test/java/com/project/SmartHomeSimulator/service/SmartHomeSecurityServiceTest.java
Labels: Delivery 2, SHP

#77 Front end update
  README.md
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/SimulationHomeSecurityController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/UserController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/HomeLayout.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SimulationContext.java
  SmartHomeSimulatorFront/.eslintrc.json
  SmartHomeSimulatorFront/.prettierrc
  SmartHomeSimulatorFront/package.json
  SmartHomeSimulatorFront/public/index.html
  SmartHomeSimulatorFront/src/Router.css
  SmartHomeSimulatorFront/src/Router.js
  SmartHomeSimulatorFront/src/appsettings.json
  SmartHomeSimulatorFront/src/components/Dashboard/Dashboard.css
  SmartHomeSimulatorFront/src/components/Dashboard/Dashboard.js
  SmartHomeSimulatorFront/src/components/EditAwayModeModal/EditAwayModeModal.js
  SmartHomeSimulatorFront/src/components/EditAwayModeModal/index.js
  SmartHomeSimulatorFront/src/components/ObjectIcon/ObjectIcon.css
  SmartHomeSimulatorFront/src/components/ObjectIcon/ObjectIcon.js
  SmartHomeSimulatorFront/src/components/ObjectIcon/index.js
  SmartHomeSimulatorFront/src/components/OutputConsole/OutputConsole.css
  SmartHomeSimulatorFront/src/components/OutputConsole/OutputConsole.js
  SmartHomeSimulatorFront/src/components/OutputConsole/index.js
  SmartHomeSimulatorFront/src/components/RoomCard/RoomCard.js
  SmartHomeSimulatorFront/src/components/SimulationFunctionalityCard/SimulationFunctionalityCard.js
  SmartHomeSimulatorFront/src/components/SimulationFunctionalityCard/index.js
  SmartHomeSimulatorFront/src/components/SimulationParameterCard/SimulationParameterCard.js
  SmartHomeSimulatorFront/src/components/SimulationProfileCard/SimulationProfileCard.js
  SmartHomeSimulatorFront/src/components/index.js
  SmartHomeSimulatorFront/src/index.js
  SmartHomeSimulatorFront/src/models/consoleMessage.js
  SmartHomeSimulatorFront/src/models/index.js
  SmartHomeSimulatorFront/src/models/simulationConfig.js
  SmartHomeSimulatorFront/src/services/index.js
  SmartHomeSimulatorFront/yarn.lock
Labels: Delivery 2, Front end

#84 chore: add console message when changing location
  SmartHomeSimulatorFront/src/components/Dashboard/Dashboard.js
  SmartHomeSimulatorFront/src/components/SimulationProfileCard/SimulationProfileCard.js
Labels: Delivery 2, Front end, bug

#101 responseAPI class refactoring
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/SimulationHomeSecurityController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/SmartHomeCoreFunctionalityController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/UserController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/ResponseAPI.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeSecurity.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/UserService.java
Labels: Delivery 3, enhancement

#103 Create Heater AC class
  HomeLayoutExample.json
  SmartHomeSimulatorBack/Class diagram.suml
  SmartHomeSimulatorBack/SmartHomeSimulator/SmartHomeHeating.txt
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/Exceptions/BlockedWindowsException.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/SimulationContextController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/SmartHomeCoreFunctionalityController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/SmartHomeHeatingController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/HomeLayout.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/Room.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/User.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/Zone.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/roomObjects/AC.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/roomObjects/Heater.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/roomObjects/RoomObject.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SimulationContext.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeCoreFunctionalityProxy.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeHeating.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeHeatingProxy.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/SimulationContextService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/SmartHomeHeatingServices.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/UserService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/test/java/com/project/SmartHomeSimulator/service/SimulationContextServiceTest.java
  SmartHomeSimulatorFront/package-lock.json
Labels: SHH
