Repository willyyhuang/soen-343, pull requests merged in 2020-12, with the labels that each got.

#104 Feature SHH
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/SimulationHomeSecurityController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/SmartHomeHeatingController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/UserController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/AwayModeMonitor.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/Module.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SimulationContext.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeCoreFunctionality.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeCoreFunctionalityProxy.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeHeating.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeHeatingProxy.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeSecurity.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeSecurityProxy.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/SmartHomeHeatingService.java
Labels: Delivery 3, SHH

#106 Setup turn on/off ac heaters
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/SmartHomeHeatingController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SimulationContext.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeHeating.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/SmartHomeHeatingService.java
Labels: Delivery 3, SHH, enhancement

#109 Setup unit test
  SmartHomeSimulatorBack/SmartHomeSimulator/.gitignore
  SmartHomeSimulatorBack/SmartHomeSimulator/SmartHomeCoreFunctionality.txt
  SmartHomeSimulatorBack/SmartHomeSimulator/SmartHomeHeating.txt
  SmartHomeSimulatorBack/SmartHomeSimulator/SmartHomeSecurity.txt
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/HomeLayout.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SimulationContext.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeHeatingProxy.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeSecurity.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/SimulationContextService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/SmartHomeCoreFunctionalityService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/SmartHomeHeatingService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/SmartHomeSecurityService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/UserService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/resources/user_profiles.json.txt
  SmartHomeSimulatorBack/SmartHomeSimulator/src/test/java/com/project/SmartHomeSimulator/service/SimulationContextServiceTest.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/test/java/com/project/SmartHomeSimulator/service/SmartHomeCoreFunctionalityServiceTest.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/test/java/com/project/SmartHomeSimulator/service/SmartHomeHeatingServiceTest.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/test/java/com/project/SmartHomeSimulator/service/SmartHomeSecurityServiceTest.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/test/java/com/project/SmartHomeSimulator/service/UserServiceTest.java
Labels: Delivery 3, SHH, Testing

#110 Repaire add zone
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/SimulationContextController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/SmartHomeHeatingController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/HomeLayout.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/ResponseParameters.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/Room.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/Zones/CompleteZones.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/Zones/Zone.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/Zones/ZoneObject.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SimulationContext.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeHeating.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeHeatingProxy.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/SimulationContextService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/SmartHomeHeatingService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/UserService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/test/java/com/project/SmartHomeSimulator/service/SmartHomeHeatingServiceTest.java
Labels: Delivery 3, SHH, bug

#116 Feature shh observer pattern
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/Room.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/User.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SimulationContext.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeHeating.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/module/SmartHomeSecurity.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/UserService.java
Labels: Delivery 3, SHH, enhancement

#118 Fix unit tests
  SmartHomeSimulatorBack/SmartHomeSimulator/src/test/java/com/project/SmartHomeSimulator/service/SimulationContextServiceTest.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/test/java/com/project/SmartHomeSimulator/service/SmartHomeSecurityServiceTest.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/test/java/com/project/SmartHomeSimulator/service/UserServiceTest.java
Labels: Delivery 3, Testing

#111 Smart Home Heating Front End
  SmartHomeSimulatorFront/package.json
  SmartHomeSimulatorFront/src/components/Dashboard/Dashboard.js
  SmartHomeSimulatorFront/src/components/ObjectIcon/ObjectIcon.js
  SmartHomeSimulatorFront/src/components/RoomCard/RoomCard.js
  SmartHomeSimulatorFront/src/components/SimulationFunctionalityCard/SimulationFunctionalityCard.js
  SmartHomeSimulatorFront/src/components/SimulationParameterCard/SimulationParameterCard.js
  SmartHomeSimulatorFront/src/components/SmartHomeHeatingCard/SmartHomeHeatingCard.js
  SmartHomeSimulatorFront/src/components/SmartHomeHeatingCard/index.js
  SmartHomeSimulatorFront/src/components/index.js
  SmartHomeSimulatorFront/src/models/index.js
  SmartHomeSimulatorFront/src/models/simulationConfig.js
  SmartHomeSimulatorFront/src/models/zone.js
  SmartHomeSimulatorFront/src/services/index.js
Labels: Delivery 3, Front end
