Repository willyyhuang/soen-343, pull requests merged in 2020-10, with the labels that each got.

#7 Add redux for state management
  SmartHomeSimulatorFront/package.json
  SmartHomeSimulatorFront/public/index.html
  SmartHomeSimulatorFront/public/manifest.json
  SmartHomeSimulatorFront/public/robots.txt
  SmartHomeSimulatorFront/src/Layout.css
  SmartHomeSimulatorFront/src/components/Login/Login.js
  SmartHomeSimulatorFront/src/font/Helvetica400.ttf
  SmartHomeSimulatorFront/src/index.js
  SmartHomeSimulatorFront/src/models/authentication.js
  SmartHomeSimulatorFront/src/models/index.js
  SmartHomeSimulatorFront/src/serviceWorker.js
  SmartHomeSimulatorFront/yarn.lock
Labels: good first issue

#17 Set up router and general authentication redirect
  .gitignore
  README.md
  SmartHomeSimulatorBack/.idea/SmartHomeSimulatorBack.iml
  SmartHomeSimulatorBack/.idea/misc.xml
  SmartHomeSimulatorBack/.idea/modules.xml
  SmartHomeSimulatorBack/.idea/vcs.xml
  SmartHomeSimulatorBack/.idea/workspace.xml
  SmartHomeSimulatorBack/SmartHomeSimulator/README.md
  SmartHomeSimulatorFront/.eslintrc.json
  SmartHomeSimulatorFront/README.md
  SmartHomeSimulatorFront/src/Layout.js
  SmartHomeSimulatorFront/src/Router.css
  SmartHomeSimulatorFront/src/Router.js
  SmartHomeSimulatorFront/src/appsettings.json
  SmartHomeSimulatorFront/src/components/Login/Login.js
  SmartHomeSimulatorFront/src/components/Login/index.css
  SmartHomeSimulatorFront/src/index.js
  SmartHomeSimulatorFront/src/models/authentication.js
  SmartHomeSimulatorFront/src/services/index.js
  SmartHomeSimulatorFront/yarn.lock
Labels: Delivery 1, documentation

#19 Login - edit users
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/UserController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/dao/UserRepository.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/User.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/UserService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/resources/application.properties
Labels: Delivery 1, enhancement

#26 Setup cross plateform
  SmartHomeSimulatorBack/SmartHomeSimulator/README.md
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/SmartHomeSimulatorApplication.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/RegistrationController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/UserController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/APIResponseLogin.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/RegistrationService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/UserService.java
  SmartHomeSimulatorFront/src/components/Login/Login.js
  SmartHomeSimulatorFront/src/models/authentication.js
  SmartHomeSimulatorFront/src/services/index.js
Labels: Delivery 1, bug

#30 Permissions - Roles
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/UserController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/Role.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/User.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/UserService.java
Labels: Delivery 1, enhancement

#32 User dashboard
  SmartHomeSimulatorFront/src/Router.js
  SmartHomeSimulatorFront/src/components/Dashboard/Dashboard.css
  SmartHomeSimulatorFront/src/components/Dashboard/Dashboard.js
  SmartHomeSimulatorFront/src/components/Dashboard/index.js
  SmartHomeSimulatorFront/src/components/Login/Login.js
  SmartHomeSimulatorFront/src/components/index.js
  SmartHomeSimulatorFront/src/models/authentication.js
  SmartHomeSimulatorFront/src/models/index.js
  SmartHomeSimulatorFront/src/models/user.js
Labels: Delivery 1, enhancement

#29 Fix Backend Validation
  SmartHomeSimulatorBack/SmartHomeSimulator/pom.xml
Labels: Delivery 1, bug

#40 Link API to UI related to Simulation Profiles
  SmartHomeSimulatorFront/.eslintrc.json
  SmartHomeSimulatorFront/package.json
  SmartHomeSimulatorFront/src/Router.js
  SmartHomeSimulatorFront/src/components/Dashboard/Dashboard.js
  SmartHomeSimulatorFront/src/components/Login/Login.js
  SmartHomeSimulatorFront/src/components/SimulationParameterCard/SimulationParameterCard.js
  SmartHomeSimulatorFront/src/components/SimulationParameterCard/index.js
  SmartHomeSimulatorFront/src/components/SimulationProfileCard/SimulationProfileCard.js
  SmartHomeSimulatorFront/src/components/SimulationProfileCard/index.js
  SmartHomeSimulatorFront/src/components/index.js
  SmartHomeSimulatorFront/src/models/index.js
  SmartHomeSimulatorFront/src/models/simulationConfig.js
  SmartHomeSimulatorFront/src/models/user.js
  SmartHomeSimulatorFront/src/services/index.js
  SmartHomeSimulatorFront/yarn.lock
Labels: Delivery 1, enhancement

#36 Simulation Profiles
  README.md
  SmartHomeSimulatorBack/.idea/SmartHomeSimulatorBack.iml
  SmartHomeSimulatorBack/.idea/misc.xml
  SmartHomeSimulatorBack/.idea/modules.xml
  SmartHomeSimulatorBack/.idea/vcs.xml
  SmartHomeSimulatorBack/.idea/workspace.xml
  SmartHomeSimulatorBack/SmartHomeSimulator/README.md
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/SimulationProfileController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/UserController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/dao/SimulationProfileRepository.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/APIResponseLogin.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/SimulationConfig.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/SimulationProfile.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/User.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/SimulationProfileService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/UserService.java
  SmartHomeSimulatorFront/.eslintrc.json
  SmartHomeSimulatorFront/package.json
  SmartHomeSimulatorFront/src/Router.js
  SmartHomeSimulatorFront/src/components/Dashboard/Dashboard.js
  SmartHomeSimulatorFront/src/components/Login/Login.js
  SmartHomeSimulatorFront/src/components/SimulationParameterCard/SimulationParameterCard.js
  SmartHomeSimulatorFront/src/components/SimulationParameterCard/index.js
  SmartHomeSimulatorFront/src/components/SimulationProfileCard/SimulationProfileCard.js
  SmartHomeSimulatorFront/src/components/SimulationProfileCard/index.js
  SmartHomeSimulatorFront/src/components/index.js
  SmartHomeSimulatorFront/src/models/index.js
  SmartHomeSimulatorFront/src/models/simulationConfig.js
  SmartHomeSimulatorFront/src/models/user.js
  SmartHomeSimulatorFront/src/services/index.js
  SmartHomeSimulatorFront/yarn.lock
Labels: Delivery 1, bug, enhancement

#41 User can load a house layout JSON file
  SmartHomeSimulatorBack/SmartHomeSimulator/pom.xml
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/UserController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/HouseLayout.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/Room.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/User.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/UserService.java
Labels: Delivery 1, enhancement

#44 remove login page, adapt new backend changes
  SmartHomeSimulatorBack/.idea/SmartHomeSimulatorBack.iml
  SmartHomeSimulatorBack/.idea/misc.xml
  SmartHomeSimulatorBack/.idea/modules.xml
  SmartHomeSimulatorBack/.idea/vcs.xml
  SmartHomeSimulatorBack/.idea/workspace.xml
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/SmartHomeSimulatorApplication.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/SimulationContextController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/HomeLayout.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/User.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/SimulationContextService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/UserService.java
  SmartHomeSimulatorFront/.gitignore
  SmartHomeSimulatorFront/debug.log
  SmartHomeSimulatorFront/package-lock.json
  SmartHomeSimulatorFront/package.json
  SmartHomeSimulatorFront/src/Router.js
  SmartHomeSimulatorFront/src/components/Dashboard/Dashboard.js
  SmartHomeSimulatorFront/src/components/Login/Login.js
  SmartHomeSimulatorFront/src/components/Login/index.css
  SmartHomeSimulatorFront/src/components/Login/index.js
  SmartHomeSimulatorFront/src/components/RoomCard/RoomCard.js
  SmartHomeSimulatorFront/src/components/RoomCard/index.js
  SmartHomeSimulatorFront/src/components/SimulationParameterCard/SimulationParameterCard.js
  SmartHomeSimulatorFront/src/components/SimulationProfileCard/SimulationProfileCard.js
  SmartHomeSimulatorFront/src/components/index.js
  SmartHomeSimulatorFront/src/images/placeholderLogo.jpg
  SmartHomeSimulatorFront/src/models/authentication.js
  SmartHomeSimulatorFront/src/models/index.js
  SmartHomeSimulatorFront/src/models/simulationConfig.js
  SmartHomeSimulatorFront/src/services/index.js
  SmartHomeSimulatorFront/yarn.lock
Labels: Delivery 1, bug, enhancement

#51 Setup unit test user service
  SmartHomeSimulatorBack/SmartHomeSimulator/pom.xml
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/HomeLayout.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/Role.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/Room.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/SimulationContext.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/User.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/SimulationContextService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/UserService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/test/java/com/project/SmartHomeSimulator/service/UserServiceTest.java
Labels: Delivery 1, Testing

#53 SimulationContextService unit tests
  SmartHomeSimulatorBack/SmartHomeSimulator/README.md
  SmartHomeSimulatorBack/SmartHomeSimulator/pom.xml
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/SimulationContextController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/api/UserController.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/HomeLayout.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/Room.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/SimulationContext.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/User.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/roomObjects/RoomObject.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/roomObjects/RoomObjectType.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/model/roomObjects/Window.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/SimulationContextService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/main/java/com/project/SmartHomeSimulator/service/UserService.java
  SmartHomeSimulatorBack/SmartHomeSimulator/src/test/java/com/project/SmartHomeSimulator/service/SimulationContextServiceTest.java
Labels: Delivery 1, Testing
